### ISSUE TITLE
#978787 感觉香港不够乱啊，请暴徒们加带力度🐶 (关注:2 评论:1)

### ISSUE THREAD

**Issue by PKUDeleted** [PKUDeleted/Holes#10668]
感觉香港不够乱啊，请暴徒们加带力度🐶
**2019-11-13 08:05:50 关注:2 评论:1**

**Comment by PKUDeleted** [comment]
**[Alice]** 这样说话真的很不负责任……dz想必是没有任何亲近的人在那边才敢说得出这种话吧。望自重。

**Comment by aironglilu** [comment]
不会错，一切的果都是当初因
